return {
  -- {
  --   "olimorris/codecompanion.nvim",
  --   config = true,
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "nvim-treesitter/nvim-treesitter",
  --   },
  --   opts = {
  --     strategies = {
  --       chat = {
  --         adapter = "githubmodels",
  --       },
  --       inline = {
  --         adapter = "copilot",
  --       },
  --     },
  --     opts = {
  --       log_level = "DEBUG",
  --     },
  --   },
  -- },
}
